repos:
  - repo: https://github.com/andreoliwa/nitpick
    rev: v0.22.2
    hooks:
      - id: nitpick

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.4
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus]

  - repo: https://github.com/asottile/yesqa
    rev: v1.1.0
    hooks:
      - id: yesqa
        additional_dependencies: [
          flake8-annotations,
          flake8-annotations-coverage,
          flake8-bandit,
          flake8-broken-line,
          flake8-bugbear,
          flake8-builtins,
          flake8-commas,
          flake8-comprehensions,
          flake8-debugger,
          flake8-eradicate,
          flake8-executable,
          flake8-fixme,
          flake8-future-import,
          flake8-pyi,
          flake8-pytest,
          flake8-pytest-style,
          flake8-mutable,
          flake8-string-format,
          flake8-todo,
          flake8-unused-arguments,
        ]

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
      - id: autoflake
        args: [
          --in-place,
          --remove-all-unused-imports,
          --remove-duplicate-keys,
          --remove-unused-variable,
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        additional_dependencies: [
          atomic-write-path >= 1.4,
          functional-itertools >= 0.11,
          joblib >= 0.15,
          pandas >= 1.0,
        ]


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: no-commit-to-branch
    - id: pretty-format-json
    - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.2
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-annotations,
          flake8-annotations-coverage,
          flake8-bandit,
          flake8-broken-line,
          flake8-bugbear,
          flake8-builtins,
          flake8-commas,
          flake8-comprehensions,
          flake8-debugger,
          flake8-eradicate,
          flake8-executable,
          flake8-fixme,
          flake8-future-import,
          flake8-pyi,
          flake8-pytest,
          flake8-pytest-style,
          flake8-mutable,
          flake8-string-format,
          flake8-todo,
          flake8-unused-arguments,
        ]
